//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dealership_BD2._2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int ID_Order { get; set; }
        public int Customer_ID { get; set; }
        public int Vehicle_ID { get; set; }
        public int Model_ID { get; set; }
        public int Brand_ID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int Amount { get; set; }
    
        public virtual Brands Brands { get; set; }
        public virtual Customers Customers { get; set; }
        public virtual Models Models { get; set; }
        public virtual Vehicles Vehicles { get; set; }
    }
}
